In [45]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 轴，就是维度，这是个二维数组，有两个轴，可以想象成一个平面
print(arr.ndim)

# 维度其实是形状，返回的是 (3,4) 三行四列
print(arr.shape)

# 元素的总数，相当于 shape 乘积
print(arr.size)

# 描述元素类型
print(arr.dtype)

# arr 类型
print(type(arr))

# 0 表示计算每一列的和，1 表示计算每一行的和
sums = arr.sum(axis=0)
print(sums)

2
(3, 4)
12
int64
<class 'numpy.ndarray'>
[15 18 21 24]


In [21]:
# 创建时显式指定类型
c = np.array([
    [1,2], 
    [3,4]
    ], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [22]:
# 创建一个由 0 组成的数组
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# 创建一个初始随机的数组
empty = np.empty((2,3))
empty

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
# 创建一个类似于 range 的数组
r = np.arange(10, 100, 5)
r

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [27]:
# 创建一个指定范围指定长度的数组
l = np.linspace(0, 2, 9)
l

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
# 打印一维数组
v1 = np.arange(12)
print(v1)

# 打印二维数组，三行四列
v2 = np.arange(12).reshape(3,4)
print(v2)

v3 = np.arange(24).reshape(2,3,4)
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
# 基本计算
a = np.array([20, 30, 40, 50])
b = np.arange(4)

print(a)
print(b)

c = a + b
d = a - b
e = b ** 2
f = a < 35

print(c)
print(d)
print(e)
print(f)


[20 30 40 50]
[0 1 2 3]
[20 31 42 53]
[20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [44]:
a = np.array([
    [1, 2],
    [0, 1]
])
b = np.array([
    [2, 0],
    [3, 4]
])

# 元素运算乘积
print(a * b)

# 矩阵乘积
print(a @ b)

[[2 0]
 [0 4]]
[[8 8]
 [3 4]]


In [48]:
# 通函数
a = np.arange(3)

print(np.sqrt(a))

print(np.min(a))

[0.         1.         1.41421356]
0


In [53]:
# 一维的数组可以直接进行索引和切片操作
a = np.arange(10)

print(a)

print(a[2])

print(a[2:])

# 多维数组以逗号分隔
b = np.array([
    [ 0,  1,  2,  3],
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43]
])

# 表示第3行，第4列的元素
print(b[2,3])

# 表示第2列的所有元素
print(b[0:5,1])

[0 1 2 3 4 5 6 7 8 9]
2
[2 3 4 5 6 7 8 9]
23
[ 1 11 21 31 41]


In [55]:
# 对多维数组进行迭代，相当于对第一个轴完成的（行）
b = np.array([
    [ 0,  1,  2,  3],
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43]
])

for row in b:
    print(row)

# 如果想对所有元素生效，则使用 flat 属性
for e in b.flat:
    print(e)    

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [76]:
# np.random.random() 函数用于生成指定大小的随机浮点数数组。生成一个2行3列的随机浮点数数组
a = np.floor(10 * np.random.random((3,4)))
print(a)

print(a.shape)

# 打平
print(a.ravel())

# 改变矩阵的形状
print(a.reshape(6,2))

# 矩阵的转置，或 a.transpose()
b = a.T
print(b)
print(b.shape)


[[3. 5. 7. 5.]
 [5. 9. 5. 8.]
 [3. 4. 1. 8.]]
(3, 4)
[3. 5. 7. 5. 5. 9. 5. 8. 3. 4. 1. 8.]
[[3. 5.]
 [7. 5.]
 [5. 9.]
 [5. 8.]
 [3. 4.]
 [1. 8.]]
[[3. 5. 3.]
 [5. 9. 4.]
 [7. 5. 1.]
 [5. 8. 8.]]
(4, 3)
